version: '2'

services:
    nodejs:
        container_name: nodejs
        build: ./docker-nodejs/
        environment:
            PROJECT_NAME: doker-nodejs
            NODE_ENV: dev
        volumes:
            - ./docker-nodejs:/usr/src/app
        ports:
            - '8080:8080'
            - '5858:5858'
        # command: "pm2 start -x --no-daemon server.js --watch"  #--daemon"
        command: "nodemon -L --debug=5858 server.js"  #--daemon"
        networks:
            - front-net
            # - back-net

    angularjs:
        container_name: angularjs
        build: ./docker-angular/
        environment:
            PROJECT_NAME: docker-angular
            NODE_ENV: "dev"
        # volumes:
            # - /home/ubuntu/working/source_code/evgroups/sokhop-frontend-cms/config/dev.json:/build/config/default.json
        ports:
            - '9000:9000'
            - '35729:35729'
        command: "grunt serve"
        networks:
            - front-net

    python:
        container_name: python
        build: ./python-flask/
        environment:
            PROJECT_NAME: python-flask
        ports:
            - '5000:5000'
        command: "python app.py"
        networks:
            - front-net

    webserver_nginx:
        container_name: webserver_nginx
        build: ./nginx/
        ports:
            - '80:80'
        # command: "nginx -g daemon off"
        networks:
            - front-net

networks:
  front-net:
#   back-net:
